### ISSUE TITLE
Example of Config?  Or Detail information on the config.inc.php?

### ISSUE THREAD

**Issue by kilimar** [tralios/Report_JUNK#1]
Would it be possible to have a sample of a working config.inc.php file or explain the needed change in more detail?  I am not sure that I understand:

```
'event_source' => '<YOUR EVENT SOURCE>',
'event_version' => 1,
'event_class' => "RawEmail",
'profile' => '<YOUR PROFILE>
```

and on blackhole.mx, it tells one to "Notice Please get in touch with us to obtain an API key for the plugin!"

What is supposed to go into the event_source and the profile?  And were does one put the API key that blackhole.mx gives you?

**Comment by tralios** [comment]
Hello danlong,

> Would it be possible to have a sample of a working config.inc.php file
> or explain the needed change in more detail? I am not sure that I
> understand:

for <YourEventSource> you can put just any string you wish. This can 
later be used to identify which of your servers/customers/whatever 
originated a report to blackhole.mx. <YourProfile> should be set to your 
domain name.

> And were does one put the API key that blackhole.mx gives you?

You can also set the API key as <YourProfile> instead of the domain 
name, but it is not necessary to obtain an API key from blackhole.mx.

Best Regards,

Dominik

## 

Tralios IT GmbH
Bannwaldallee 46
76185 Karlsruhe

Telefon: 07 21 - 94 26 96 60
Telefax: 07 21 - 94 26 96 66

E-Mail: info@tralios.de
Homepage: https://www.tralios.de

Registergericht: Amtsgericht Mannheim
Registernummer: HRB 710690

USt-ID: DE274667358

Vertretungsberechtigte Geschäftsführer:
Dipl.-Inform. Dominik Vallendor
Dipl.-Inform. Carl Thomas Witzenrath

**Comment by kilimar** [comment]
Thank you!

 -d
